### ISSUE TITLE
The link to the toolchain-specification in the description of the toolchain input is broken

### ISSUE THREAD

**Issue by MindSwipe** [actions-rs/toolchain#115]
The current link in [action.yml](https://github.com/actions-rs/toolchain/blob/3639e8fd467987569a9b77ada78802df6e30169c/action.yml#L12) points to 
> https://github.com/rust-lang/rustup.rs#toolchain-specification

This  however doesn't exist any more, as it has been moved to the book under the chapter `Toolchain specifications` here 

>https://rust-lang.github.io/rustup/concepts/toolchains.html#toolchain-specification

**Comment by svartalf** [comment]
Closed by #116
