### ISSUE TITLE
Action seems to ignore rust-toolchain files

### ISSUE THREAD

**Issue by jack-signal** [actions-rs/toolchain#123]
Do the checklist before filing an issue:

 * [x] Is this related to the `actions-rs` Actions?
       If you think it's a problem related to Github Actions in general, use GitHub Community forum instead: https://github.community
 * [x] You've read the Contributing section about bugs reporting: https://github.com/actions-rs/.github/blob/master/CONTRIBUTING.md#reporting-bugs
 * [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome.

## Description

It does not seem that `rust-toolchain` files are read.

## Workflow code

https://github.com/jack-signal/gh-actions-test/blob/5666895d3ee0ca51506901b09d6d94a8758e8e9a/.github/workflows/rust.yml

Relevant part
```yaml
    - name: Install nightly rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        components: rustfmt, clippy
```
 
## Action output

Full log with debug on here https://github.com/jack-signal/gh-actions-test/runs/1376041496

```
##[debug]Evaluating condition for step: 'Install nightly rust'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Install nightly rust
##[debug]Loading inputs
##[debug]Loading env
Run actions-rs/toolchain@v1
  with:
    profile: minimal
    components: rustfmt, clippy
    default: false
    override: false
  env:
    CARGO_TERM_COLOR: always
Error: toolchain input was not given and repository does not have a rust-toolchain file
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Install nightly rust
```

## Expected behavior

The problem here is - the repository *does have* a `rust-toolchain` file in the root directory, so I would expect that it would be used.

**Comment by svartalf** [comment]
Hi, @jack-signal! You still need to check out your code first, otherwise there are no files at all at the working directory.

Please, see `actions/checkout@v2` line at the [example workflow](https://github.com/actions-rs/toolchain#example-workflow) and to [GH Actions documentation](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/introduction-to-github-actions#understanding-the-workflow-file)

**Comment by jack-signal** [comment]
Oh my gosh I can't believe I missed that, thank you.
