### ISSUE TITLE
deperecated dependency: 100% failure 

### ISSUE THREAD

**Issue by bilelmoussaoui** [actions-rs/toolchain#124]
Do the checklist before filing an issue:

 * [x] Is this related to the `actions-rs` Actions?
       If you think it's a problem related to Github Actions in general, use GitHub Community forum instead: https://github.community
 * [x] You've read the Contributing section about bugs reporting: https://github.com/actions-rs/.github/blob/master/CONTRIBUTING.md#reporting-bugs
 * [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome.

## Description

See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

and https://github.com/actions-rs/toolchain/pull/114 for a PR that fixes the issue

## Workflow code

```yaml
Paste that part of your workflow yaml file that causes the bug in here.

Alternatively you can remove that code block and insert direct link to your workflow file.
Ensure that link points to the specific commit, and not just to the master branch.
```
 
## Action output

```
/usr/bin/docker exec  d25f5c30aa8e784012badcab5bc6344c4bce5a4c72f595ca756380dfab46bd95 sh -c "cat /etc/*release | grep ^ID"
/__w/_temp/42a68bee-6546-42ed-9628-d75de2498306 --default-toolchain none -y
info: downloading installer
error: $HOME differs from euid-obtained home directory: you may be using sudo
error: $HOME directory: /github/home
error: euid-obtained home directory: /root
info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
info: skipping toolchain installation


Rust is installed now. Great!

To get started you need Cargo's bin directory ($HOME/.cargo/bin) in your PATH
environment variable. Next time you log in this will be done
automatically.

To configure your current shell run source $HOME/.cargo/env
Error: Unable to process command '::add-path::/github/home/.cargo/bin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

```

## Expected behavior

The `$PATH` to be properly set

## Additional context

This will causes a lot of breakages out there I guess :P

**Comment by wez** [comment]
There's more to resolving this than just bumping the dep.

Here's the workaround I'm going to use for the moment:

```diff
diff --git a/.github/workflows/gen_centos7.yml b/.github/workflows/gen_centos7.yml
index 94fefcb6..8419966d 100644
--- a/.github/workflows/gen_centos7.yml
+++ b/.github/workflows/gen_centos7.yml
@@ -53,12 +53,14 @@ jobs:
       shell: bash
       run: "git fetch --prune --unshallow"
     - name: "Install Rust"
-      uses: actions-rs/toolchain@v1
+      uses: actions-rs/toolchain@dependabot/npm_and_yarn/actions/core-1.2.6
       with:
          profile: "minimal"
          toolchain: "stable"
          override: true
          components: "rustfmt"
+      env:
+         ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
     - name: "Cache cargo"
       uses: actions/cache@v2
       with:
```

I think the full and righteous fix is to update the dep and to adjust the action to use the environment file mentioned on the linked documentation.

**Comment by wez** [comment]
I would advocate for renaming this issue: `actions-rs/toolchain 100% failure rate for all users" so that it doesn't get lost in the dependabot noise.

**Comment by bilelmoussaoui** [comment]
> I would advocate for renaming this issue: `actions-rs/toolchain 100% failure rate for all users` so that it doesn't get lost in the dependabot noise.

Thanks. I have been looking at the source code on where the add-path is used without any luck.

**Comment by sergeyzenchenko** [comment]
This issue is happening because of rustup. The fix was merged at Oct 16 https://github.com/rust-lang/rustup/pull/2513

**Comment by svartalf** [comment]
Thank you for notification, @bilelmoussaoui! Fix was added and released as a new `@v1` version; I apologize for not handling this deprecation issue earlier.

Can anyone in this thread additionally confirm that it works for them now?

**Comment by bilelmoussaoui** [comment]
@svartalf thanks a lot for the quick fix, can confirm it works fine now :+1:
