### ISSUE TITLE
Support for rust-toolchain.toml

### ISSUE THREAD

**Issue by itamarst** [actions-rs/toolchain#208]
Do the checklist before filing an issue:

 * [x] Is this related to the `actions-rs` Actions?
       If you think it's a problem related to Github Actions in general, use GitHub Community forum instead: https://github.community
 * [x] You've read the Contributing section about feature requests: https://github.com/actions-rs/.github/blob/master/CONTRIBUTING.md#feature-requests
 * [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome.

## Motivation

`rust-toolchain.toml` is the new improved version of `rust-toolchain`. It also allows specifying components: https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file

## Workflow example

Much like `rust-toolchain` is auto-detected, so should the `rust-toolchain.toml` file. Components should be respected as well.

Thank you!

**Comment by Imberflur** [comment]
Is this a duplicate of #126?

**Comment by itamarst** [comment]
Guess I missed it, sorry, yes.
