### ISSUE TITLE
`--default-host` is not equivalent to `toolchain add`

### ISSUE THREAD

**Issue by nagisa** [actions-rs/toolchain#8]
When using this action with `target: ...-ios` on `macos-latest`, this action invokes:

```
$ /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/rustup-init.sh -y --default-toolchain nightly --default-host armv7-apple-ios
```

which promptly fails.

```
...
error: target 'armv7-apple-ios' not found in channel.  Perhaps check https://forge.rust-lang.org/platform-support.html for available targets
```

This action should be using `rustup toolchain add` always.

**Comment by svartalf** [comment]
@nagisa, thanks for a bug report! You are right, this behavior is incorrect. Could you test a branch with fix for it? All you need is to change the
```yaml
- uses: actions-rs/toolchain@v1
```
to 
```yaml
- uses: actions-rs/toolchain@toolchain-add
```
temporary and re-run the workflow.

**Comment by nagisa** [comment]
Testing right now.

**Comment by nagisa** [comment]
Alas, action from the branch fails with a javascript error. [see the run](https://github.com/rust-lang/stacker/runs/249182890) (or the [raw logs](https://pipelines.actions.githubusercontent.com/GWM5xcVGaaosNKNURCkrFIb5vvfpdP9A7swSL6HxcKzzCPCShb/_apis/pipelines/1/runs/50/signedlogcontent/42?urlExpires=2019-10-05T19%3A21%3A16.3164290Z&urlSigningMethod=HMACV1&urlSignature=CpWhkNIynrPsa9CVbaDYBwL3lfVxmtcDJ7Fw2wy5V7I%3D))

**Comment by svartalf** [comment]
@nagisa hm, yes, my bad, there is something with a build process for Action. I rebuilt it, copied your workflow config for iOS build and executed it [here](https://github.com/actions-rs/example/runs/249210250); seems like a cross-compilation works fine now. Could you also re-run your build too, just to be sure?

**Comment by nagisa** [comment]
Appears to be working now :ship:

**Comment by svartalf** [comment]
Published it as a next version, you can switch back to the `actions-rs/toolchain@v1` now, thank you for a bug report!
